[package]
name = "hello_cargo"
version = "0.1.0"
edition = "2021"
authors = ["Romain Bayle <5014@holbertonstudents.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
